apiVersion: v1
kind: Namespace
metadata: 
  name: webapp-demo
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-demo
  namespace: webapp-demo
spec:
  selector:
    app: webapp-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-demo-deployment
  namespace: webapp-demo
  labels:
    app: webapp-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-demo
  template:
    metadata:
      labels:
        app: webapp-demo
    spec:
      containers:
      - name: webapp-demo
        image: virtualthoughts/circleci-webappdemo:0.1.114
        ports:
        - containerPort: 80